# Generated by Django 4.1.9 on 2023-07-13 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guruh_nom', models.CharField(max_length=50)),
                ('ochilgan_sana', models.DateField()),
                ('davomiyligi', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Hujatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('ochilgan_sana', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=35)),
                ('fam', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=13)),
                ('manzil', models.CharField(max_length=60)),
                ('tugulgan_sana', models.DateField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sorov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('fam', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=13)),
                ('sorov_qoldirilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('kurs_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.kurs')),
            ],
        ),
        migrations.CreateModel(
            name='Sinov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guruh_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.guruh')),
                ('kurs_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.kurs')),
                ('sorov_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.sorov')),
            ],
        ),
        migrations.CreateModel(
            name='Kutish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batafsil', models.TextField()),
                ('sorov_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.sorov')),
            ],
        ),
        migrations.AddField(
            model_name='guruh',
            name='kurs_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.kurs'),
        ),
        migrations.CreateModel(
            name='Darslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guruh_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.guruh')),
                ('kurs_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.kurs')),
                ('teacher_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.teacher_table')),
            ],
        ),
        migrations.CreateModel(
            name='Asosiy_talabalar_safi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=35)),
                ('fam', models.CharField(max_length=50)),
                ('tel_1', models.CharField(max_length=13)),
                ('tel_2', models.CharField(max_length=13)),
                ('rasm', models.FileField(blank=True, null=True, upload_to='')),
                ('tugulgan_joy', models.CharField(max_length=60)),
                ('tugulgan_sana', models.DateField()),
                ('guruh_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.guruh')),
                ('kurs_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.kurs')),
            ],
        ),
    ]
