# Generated by Django 4.1.9 on 2023-07-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_remove_sinov_sorov_fk_sinov_kutish_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinov',
            name='vaqt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
