# Generated by Django 4.1.9 on 2023-07-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_sinov_vaqt'),
    ]

    operations = [
        migrations.AddField(
            model_name='darslar',
            name='dars_boshlanish_vaqti',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='darslar',
            name='hafta_kunlari',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
