# Generated by Django 4.1.9 on 2023-09-10 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_darslar_dars_boshlanish_vaqti_darslar_hafta_kunlari'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.IntegerField()),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('tolov_qilgan_shaxs', models.CharField(max_length=60)),
                ('asosiy_talabalar_safi_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.asosiy_talabalar_safi')),
            ],
        ),
    ]
