# Generated by Django 4.1.9 on 2023-09-12 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_tolov'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs_summa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.SmallIntegerField()),
                ('kurs_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.kurs')),
            ],
        ),
    ]
