# Generated by Django 4.1.9 on 2023-09-17 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0007_yechib_olish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yechib_olish',
            name='tolov_fk',
        ),
        migrations.AddField(
            model_name='yechib_olish',
            name='asosiy_talabalar_safi_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.asosiy_talabalar_safi'),
        ),
    ]
