# Generated by Django 4.1.9 on 2023-09-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0009_tolov_umumiy_summa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolov',
            name='umumiy_summa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
