# Generated by Django 4.1.9 on 2023-09-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0011_remove_tolov_umumiy_summa_umumiy_shot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolov',
            name='tolov_qilgan_shaxs_tel',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
