# Generated by Django 4.1.9 on 2023-09-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0012_tolov_tolov_qilgan_shaxs_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harajat_turi', models.CharField(max_length=50)),
                ('summa', models.IntegerField()),
                ('tarif', models.TextField()),
                ('vaqt', models.DateTimeField()),
            ],
        ),
    ]
