# Generated by Django 4.1.9 on 2023-09-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0013_harajat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harajat',
            name='vaqt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
