# Generated by Django 4.1.9 on 2023-09-21 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0014_alter_harajat_vaqt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor_oylik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oy_nomi', models.CharField(max_length=25)),
                ('summa', models.IntegerField()),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('mentor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.teacher_table')),
            ],
        ),
    ]
