# Generated by Django 4.1.9 on 2023-09-26 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0015_mentor_oylik'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReklamaMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(upload_to='')),
                ('tarif', models.TextField()),
                ('teacher_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.teacher_table')),
            ],
        ),
    ]
