# Generated by Django 4.1.9 on 2023-09-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0016_reklamamentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReklamaAlochiOquvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=25)),
                ('fam', models.CharField(max_length=25)),
                ('tarif', models.TextField()),
                ('rasm', models.FileField(upload_to='')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
