# Generated by Django 4.1.9 on 2023-09-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0017_reklamaalochioquvchilar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('rasm', models.FileField(upload_to='')),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
