# Generated by Django 4.1.9 on 2023-09-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0018_yangiliklar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elonlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('tarif', models.TextField()),
                ('boshlanish_vaqti', models.DateField()),
            ],
        ),
    ]
