# Generated by Django 4.1.9 on 2023-10-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0019_elonlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hujatlar',
            name='file',
            field=models.FileField(upload_to='hujatlar/'),
        ),
    ]
