# Generated by Django 4.1.9 on 2023-10-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0020_alter_hujatlar_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='hujatlar',
            name='tarif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
