# Generated by Django 4.1.9 on 2023-10-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0021_hujatlar_tarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hujatlar',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
