# Generated by Django 4.1.9 on 2023-10-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0022_alter_hujatlar_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirif_matn', models.CharField(max_length=60)),
                ('joylashuv', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=13)),
                ('quyi_matn', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mentor_oylik',
            name='soha',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
