# Generated by Django 4.1.9 on 2023-10-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0024_remove_mentor_oylik_soha_reklamamentor_soha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklamamentor',
            name='rasm',
            field=models.FileField(upload_to='reklama_mentor_rasmlari/'),
        ),
    ]
