# Generated by Django 4.1.9 on 2023-10-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0025_alter_reklamamentor_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='reklamaalochioquvchilar',
            name='sertifikat',
            field=models.FileField(blank=True, null=True, upload_to='sertifikatlar'),
        ),
        migrations.AlterField(
            model_name='reklamaalochioquvchilar',
            name='rasm',
            field=models.FileField(upload_to='talaba_rasm'),
        ),
    ]
