# Generated by Django 4.1.9 on 2023-10-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0026_reklamaalochioquvchilar_sertifikat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangiliklar',
            name='rasm',
            field=models.FileField(upload_to='yangiliklar_rasm'),
        ),
    ]
