# Generated by Django 4.1.9 on 2023-10-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0027_alter_yangiliklar_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hujatlar',
            name='file',
            field=models.FileField(upload_to='hujat'),
        ),
    ]
