# Generated by Django 4.1.9 on 2023-10-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0028_alter_hujatlar_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='tarif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
