# Generated by Django 4.1.9 on 2023-11-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0029_info_tarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='shirif_matn',
            field=models.CharField(max_length=100),
        ),
    ]
