# Generated by Django 4.1.9 on 2023-11-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0030_alter_info_shirif_matn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='shirif_matn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
