from django.contrib import admin
from .models import *

admin.site.register(Kurs)
admin.site.register(Sorov)
admin.site.register(Guruh)
admin.site.register(Kutish)
admin.site.register(Sinov)
admin.site.register(Asosiy_talabalar_safi)
admin.site.register(Hujatlar)
admin.site.register(Teacher_table)
admin.site.register(Darslar)
admin.site.register(Tolov)
admin.site.register(Kurs_summa)
admin.site.register(Yechib_olish)
admin.site.register(Umumiy_shot)
admin.site.register(Harajat)
admin.site.register(Mentor_oylik)
admin.site.register(ReklamaMentor)
admin.site.register(ReklamaAlochiOquvchilar)
admin.site.register(Yangiliklar)
admin.site.register(Elonlar)
