from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('IndexAdmin/', IndexAdmin.as_view()),
    path('kurslar/', Kurslar.as_view()),
    path('kursdelete/<int:son>', KursDelete.as_view()),
    path('guruhlar/', Guruhlar.as_view()),
    path('sorov/', Sorovlar.as_view()),
    path('kutayotganlar/', Kutayotganlar.as_view()),
    path('guruhdelete/<int:son>', GuruhDelete.as_view()),
    path('sinov/', Sinovv.as_view()),
    path('talabalar/', Talabalar.as_view()),
    path('davomat/', DavomatAdmin.as_view()),
    path('hujat/', Hujat.as_view()),
    path('hujatochish/<int:pk>/', HujatOchish),
    path('hujatdelete/<int:pk>', HujatDelete),
    path('teacher/', Teacher.as_view()),
    path('dars/', Dars.as_view()),
    path('sorovdelete/<int:pk>', SorovDelete),
    path('kutushdelete/<int:pk>', KutushDelete),
    path('sinovdelete/<int:pk>', SinovDelete),
    path('talabadelete/<int:pk>', TalabaDelete),
    path('teacherdelete/<int:pk>', TeacherDelete),
    path('moliya/', Moliya.as_view()),
    path('shot/<int:pk>', Shot.as_view()),
    path('yechibOlish/', Yechib_olishsh.as_view()),
    path('kursSummasi/', KursSummasi.as_view()),
    path('qarizdorlarJadvali/', Qarizdorlar_jadvali.as_view()),
    path('moliyaKirim/', MoliyaKirim.as_view()),
    path('harajatlarKiritish/', Harajatlar_kiritish.as_view()),
    path('barchaHarajatlar/', Barcha_Harajatlar.as_view()),
    path('moliyaDiagramma/', MoliyaDiagramma.as_view()),
    path('oqituvchi_oyligi/', Oqituvchi_oyligi.as_view()),
    path('oylikChiqim/', Oylik_jadval.as_view()),
    path('imkonyatlar/', Imkoniyatlar.as_view()),
    path('smsjonatish/', Qarizdorlar_SMS.as_view()),

    path('foydalanuvchiSahifasi/', FoydalanuvchiSahifasi.as_view()),
    path('reklamamentor/', ReklamaMentorr.as_view()),
    path('reklamaMentorDel/<int:pk>', MentorDelete),
    path('yangiliklar/', YangiliklarIndex.as_view()),
    path('reklamaoquvchilar/', ReklamaOquvchilar.as_view()),
    path('reklamaoquvchiDel/<int:pk>', ReklamaOquvchiDel),
    path('yangiliklarSayt/', Yangiliklarr.as_view()),
    path('yangiliklarSaytDel/<int:pk>', YangiliklarDel),
    path('elonlarSayt/', ElonlarSayt.as_view()),
    path('elonSaytDell/<int:pk>', ElonSytDel),
    path('infoDel/<int:pk>', IndexDell)
]
