# Generated by Django 4.1.9 on 2023-07-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomat',
            name='vaqt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
