# Generated by Django 4.1.9 on 2023-07-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_alter_davomat_vaqt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='davomat',
            old_name='darsga_qatnashdi',
            new_name='darsga_qatnashmadi',
        ),
    ]
