# Generated by Django 4.1.9 on 2023-07-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_sinov_vaqt'),
        ('mentor', '0003_rename_darsga_qatnashdi_davomat_darsga_qatnashmadi'),
    ]

    operations = [
        migrations.AddField(
            model_name='davomat',
            name='teacher_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.teacher_table'),
        ),
    ]
