# Generated by Django 4.1.9 on 2023-07-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_darslar_dars_boshlanish_vaqti_darslar_hafta_kunlari'),
        ('mentor', '0004_davomat_teacher_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='baholash',
            name='teacher_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.teacher_table'),
        ),
        migrations.AddField(
            model_name='konfrensiya',
            name='teacher_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.teacher_table'),
        ),
        migrations.AddField(
            model_name='mavzu',
            name='teacher_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.teacher_table'),
        ),
    ]
