# Generated by Django 4.1.9 on 2023-07-26 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_darslar_dars_boshlanish_vaqti_darslar_hafta_kunlari'),
        ('mentor', '0005_baholash_teacher_fk_konfrensiya_teacher_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konfrensiya',
            name='guruh',
        ),
        migrations.AddField(
            model_name='konfrensiya',
            name='guruh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.guruh'),
        ),
    ]
