# Generated by Django 4.1.9 on 2023-07-31 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_darslar_dars_boshlanish_vaqti_darslar_hafta_kunlari'),
        ('mentor', '0007_konfrensiya_soat_alter_konfrensiya_vaqt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eslatma', models.TextField()),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('teacher_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.teacher_table')),
            ],
        ),
    ]
